// export const categories = [
//   // 📚 Literature & Books
//   "Classic Literature",
//   "Modern Fiction",
//   "Fantasy World-Building",
//   "Science Fiction Futures",
//   "Japanese Literature",
//   "Russian Novels",
//   "Book Reviews & Essays",
//   "Poetry Analysis",
//   "Literary Theory",
//   "Graphic Novels & Comics",

//   // 🧪 Science & Nature
//   "Astrophysics",
//   "Neuroscience",
//   "Genetics & Biotechnology",
//   "Climate Science",
//   "Quantum Mechanics",
//   "Animal Behavior",
//   "Geology & Earth Systems",
//   "Oceanography",
//   "Botany & Plant Science",
//   "Evolutionary Biology",
//   "Ecology & Conservation",
//   "Microbiology",
//   "Materials Science",
//   "Astronomy & Telescopes",

//   // ⚙️ Engineering & Technology
//   "Artificial Intelligence Ethics",
//   "Machine Learning Models",
//   "Blockchain & Web3",
//   "Space Exploration Tech",
//   "Augmented Reality Design",
//   "Cybersecurity Trends",
//   "Quantum Computing",
//   "Tech Startup Culture",
//   "Open Source Software",
//   "Human-Computer Interaction",
//   "Mechanical Engineering",
//   "Civil Infrastructure",
//   "Electrical Systems",
//   "Robotics & Automation",
//   "Clean Energy Engineering",

//   // 🎨 Art & Design
//   "Impressionist Painting",
//   "Digital Illustration",
//   "Street Art & Graffiti",
//   "Concept Art & Game Design",
//   "Art History: Renaissance",
//   "Typography & Font Design",
//   "Photography Composition",
//   "Minimalist Aesthetics",
//   "Ceramic Arts",
//   "Calligraphy & Lettering",
//   "Fashion Illustration",
//   "Architectural Sketching",

//   // 🧠 Philosophy & Psychology
//   "Existential Philosophy",
//   "Behavioral Psychology",
//   "Cognitive Biases",
//   "Stoicism & Ancient Wisdom",
//   "Consciousness Studies",
//   "Jungian Archetypes",
//   "Moral Philosophy",
//   "Social Psychology",
//   "Mindfulness & Meditation",
//   "Psychedelic Science",

//   // 📖 History & Culture
//   "Ancient Egypt",
//   "World War II Tactics",
//   "Medieval Europe",
//   "Samurai Culture",
//   "Indigenous Histories",
//   "Colonial India",
//   "Cold War Politics",
//   "Renaissance Italy",
//   "Civil Rights Movement",
//   "Mythology & Folklore",
//   "Post-Colonial Studies",
//   "History of the Silk Road",
//   "Women in History",

//   // 🌍 Cultural Identity & Studies
//   "Afrofuturism",
//   "Latin American Storytelling",
//   "South Asian Diaspora",
//   "Arabic Calligraphy & Poetry",
//   "Aboriginal Art & Culture",
//   "Eastern European Folklore",
//   "Chinese Philosophy",
//   "Native American Wisdom",
//   "Korean Pop Culture",
//   "African Oral Traditions",

//   // 🧘 Wellness & Lifestyle
//   "Holistic Health Practices",
//   "Sleep Optimization",
//   "Yoga Philosophy",
//   "Nutrition Science",
//   "Digital Minimalism",
//   "Emotional Intelligence",
//   "Biohacking",
//   "Self-Compassion Techniques",
//   "Productivity Rituals",
//   "Longevity Research",

//   // ⚽ Sports & Games
//   "Football (Soccer)",
//   "Basketball Tactics",
//   "Olympic Gymnastics",
//   "Martial Arts: Jiu-Jitsu",
//   "Cricket Strategies",
//   "Surfing Culture",
//   "Formula 1 Racing",
//   "Tennis Grand Slams",
//   "Chess Endgames",
//   "Esports & Competitive Gaming",
//   "Rock Climbing Techniques",
//   "Table Tennis Strategy",
//   "Athletic Psychology",

//   // 🎶 Music & Performance
//   "Jazz Improvisation",
//   "Classical Music Analysis",
//   "Hip-Hop Lyricism",
//   "Electronic Music Production",
//   "Music Theory Basics",
//   "Opera & Vocal Training",
//   "World Music Traditions",
//   "Film Scoring",
//   "Street Performance",
//   "Instrument Craftsmanship",

//   // 🍽 Food & Culture
//   "Japanese Washoku",
//   "French Pastry Techniques",
//   "Street Food Stories",
//   "Fermentation & Pickling",
//   "Coffee Roasting",
//   "Wine Tasting Regions",
//   "Plant-Based Nutrition",
//   "Ancient Food Rituals",
//   "Global Spice Trade",
//   "Indigenous Food Knowledge",
//   "Nordic Cuisine",
//   "Molecular Gastronomy",

//   // ✈️ Travel & Geography
//   "Hidden Cities of Europe",
//   "Mountain Cultures",
//   "Island Life in the Pacific",
//   "National Parks of Africa",
//   "Sacred Pilgrimages",
//   "Nomadic Traditions",
//   "Scandinavian Landscapes",
//   "Historical Trade Routes",
//   "Travel Writing & Photography",
//   "Desert Ecosystems",

//   // 🎮 Gaming & Digital Culture
//   "Open World RPGs",
//   "Speedrunning Culture",
//   "Game Lore & Storytelling",
//   "Retro Video Games",
//   "Twitch Streaming Strategy",
//   "Indie Game Development",
//   "Mobile Game UX",
//   "Gamification in Learning",
//   "VR Game Design",
//   "Narrative Design in Games",

//   // 🧾 Economics, Business & Law
//   "Behavioral Economics",
//   "Global Trade Policies",
//   "Cryptocurrency Regulation",
//   "Antitrust Law",
//   "Digital Marketing Strategy",
//   "Freelancer Economics",
//   "Startup Fundraising",
//   "Corporate Governance",
//   "Intellectual Property Law",
//   "Impact Investing",

//   // 🧑‍🏫 Education & Learning
//   "Learning Science",
//   "Alternative Education Models",
//   "EdTech Tools",
//   "Montessori Philosophy",
//   "Language Acquisition",
//   "Cognitive Load Theory",
//   "Critical Thinking Curriculum",
//   "Educational Neuroscience",
//   "Self-Taught Paths",
//   "Homeschooling Frameworks",
// ];

const categories = [
  "Artificial Intelligence",
  "AI Conspiracy Theories",
  "Technology & Future Tech",
  "Quantum Theory",
  "String Theory",
  "Multiverse & Alternate Realities",
  "Simulation Theory",
  "Time Travel & Paradoxes",
  "Existence of Aliens",
  "UFOs & Government Disclosures",
  "Ancient Aliens",
  "Lost Civilizations",
  "Ancient Technology",
  "Secret Government Projects",
  "Mind Control & MK-Ultra",
  "CERN & The Large Hadron Collider",
  "Dark Matter & Antimatter",
  "Zero-Point Energy",
  "Consciousness & Reality",
  "Lucid Dreaming & Astral Projection",
  "Remote Viewing & ESP",
  "Unexplained Phenomena",
  "Mysteries of the Universe",
  "Conspiracy Theories",
  "Hidden History",
  "Historical Disasters & Incidents",
  "Nuclear Events (Chernobyl, Hiroshima)",
  "Interdimensional Beings",
  "Existential Risks",
  "Philosophy of Existence",
  "Transhumanism & Biohacking",
];

export const randomCategoryFetcher = () => {
  return categories[Math.floor(Math.random() * categories.length)];
};
